version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=yoophi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - '8088:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
volumes:
  pg_data:
  pgadmin_data:
